<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/jquery-3.2.1.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/createjs-2015.11.26.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/screenfull.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/platform.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/ios_fullscreen.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/howler.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/ctl_utils.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/sprite_lib.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/settings.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CGameSettings.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CFichesController.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CLang.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CPreloader.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CMain.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CTextButton.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CGfxButton.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CFicheBut.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CBetTableButton.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CToggle.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CMenu.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CGame.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CInterface.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CMsgBox.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CTweenController.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CSeat.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CTableController.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CEnlight.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CFiche.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CDicesAnim.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CGameOver.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CCreditsPanel.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CRollingTextController.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CPuck.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CDicesTopDownView.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CAreYouSurePanel.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CScoreText.js') }}"></script>
<script type="text/javascript" src="{{ asset('storage/Games/Craps/js/CCTLText.js') }}"></script>