<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/jquery-3.2.1.min.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/createjs-2015.11.26.min.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/howler.min.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/screenfull.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/platform.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/ios_fullscreen.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/ctl_utils.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/sprite_lib.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/settings.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CRouletteSettings.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CFichesController.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CLang.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CPreloader.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CMain.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CTextButton.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CGfxButton.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CFicheBut.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CBetTableButton.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CBetTextButton.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CToggle.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CMenu.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CGame.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CInterface.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CMsgBox.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CTweenController.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CSeat.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CTableController.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CEnlight.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CWheelTopAnim.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CFiche.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CHistoryRow.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CWheelAnim.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CFinalBetPanel.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CNeighborsPanel.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CGameOver.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CCreditsPanel.js') }} "></script>
<script type="text/javascript" src="{{asset('storage/Games/Roulette/js/CCTLText.js') }} "></script>