<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/jquery-3.2.1.min.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/createjs-2015.11.26.min.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/howler.min.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/screenfull.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/platform.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/ios_fullscreen.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/ctl_utils.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/sprite_lib.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/settings.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CSlotSettings.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CLang.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CPreloader.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CMain.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CTextButton.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CGfxButton.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CToggle.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CBetBut.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CMenu.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CGame.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CReelColumn.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CInterface.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CPayTablePanel.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CStaticSymbolCell.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CTweenController.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CCreditsPanel.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CCTLText.js') }} "></script>
<script type="text/javascript" src=" {{ asset('storage/Games/SlotMachine/js/CRechargePanel.js') }} "></script>